# SwiftLint configuration for Ackbar

included:
  - ackbar.swift

excluded:
  - .build
  - Ackbar.app

# Rule configuration
opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

disabled_rules:
  - todo
  - line_length
  - file_length
  - type_body_length
  - function_body_length

analyzer_rules:
  - unused_import
  - unused_declaration

# Custom rules
custom_rules:
  no_direct_exit:
    name: "No Direct Exit"
    regex: "exit\\([0-9]\\)"
    match_kinds:
      - identifier
    message: "Avoid using exit() directly except in CLI flag handlers"
    severity: warning

# Rule parameters
force_cast: error
force_try: error
force_unwrapping: error

trailing_whitespace:
  ignores_empty_lines: true

vertical_whitespace:
  max_empty_lines: 2

identifier_name:
  excluded:
    - id
    - x
    - y

cyclomatic_complexity:
  ignores_case_statements: true

nesting:
  type_level: 2
  function_level: 3

file_header:
  required_pattern: |
    \/\/
    \/\/ .*\.swift
    \/\/ A lightweight macOS menu bar manager
    \/\/